luigid:
  restart: always
  build: ./luigid/
 # image: zhc/luigid3
  ports:
    - "8082:8082"
  links:
    - mysql:mysql
  volumes:
    - /usr/local/lib/python2.7/site-packages/luigi/static/visualiser


nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - luigid
  links:
    - luigid:luigid

mysql:
  restart: always
  image: mysql:latest
  volumes:
    - /var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: luigid
    MYSQL_USER: admin
    MYSQL_PASSWORD: lu1g1p4ss
    MYSQL_ROOT_PASSWORD: root

# data:
#   restart: always
#   image: ubuntu:latest
#   volumes:
#     - /var/lib/mysql
#   command: true
